# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  docker-arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: uname -a
      - run: echo "Hello, Arm!"
      - checkout
      - run: docker version
      - run:
          name: "docker-release-minimal"
          command: "DOCKER_BUILDKIT=1 docker build -t leafnunes/fpm --build-arg BASE_ENV=minimal --build-arg TARGET=release ."
      - run: docker inspect leafnunes/fpm
      
  docker-amd64:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:2021.04
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: "docker-release-minimal"
          # command pulled from Makefile, since no make installed on docker builder image
          command: "DOCKER_BUILDKIT=1 docker build -t leafnunes/fpm  --build-arg BASE_ENV=minimal --build-arg TARGET=release ."
      - run: docker inspect leafnunes/fpm

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  docker-images-workflow:
    jobs:
      - docker-arm64
#      - docker-amd64
